SELECT cc.CASE_NUMBER, cc.PRIMARY_TYPE AS CRIME, csd.COMMUNITY_AREA_NAME
FROM chicago_crime cc
LEFT JOIN chicago_socioeconomic_data csd
ON cc.COMMUNITY_AREA_NUMBER = csd.COMMUNITY_AREA_NUMBER
WHERE LOWER(cc.LOCATION_DESCRIPTION) LIKE '%school%';