SELECT JOB_TITLE, JOB_IDENT, MIN_SALARY, MAX_SALARY,
(
	SELECT EMP_ID 
    FROM EMPLOYEES 
    WHERE JOBS.JOB_IDENT = EMPLOYEES.JOB_ID) AS EMP_ID,
(
	SELECT F_NAME
    FROM EMPLOYEES
    WHERE JOBS.JOB_IDENT = EMPLOYEES.JOB_ID) AS F_NAME,
(
	SELECT L_NAME
    FROM EMPLOYEES
    WHERE JOBS.JOB_IDENT = EMPLOYEES.JOB_ID) AS L_NAME,
(
	SELECT SALARY
    FROM EMPLOYEES
    WHERE JOBS.JOB_IDENT = EMPLOYEES.JOB_ID) AS SALARY
FROM JOBS
WHERE JOB_IDENT IN (SELECT JOB_ID FROM EMPLOYEES WHERE YEAR(B_DATE) > 1976);